### ISSUE TITLE
No longer works with Sketch 45

### ISSUE THREAD

**Issue by craigmdennis** [nefaurk/select-parent-artboards#4]

**Comment by nefaurk** [comment]
Thanks for filing this issue! I'm currently looking into this. It seems like there may have been some API changes in Sketch 45.

**Comment by craigmdennis** [comment]
I've just discovered that `ESC` now does the same as this plugin (I believe), in that it selects the parent artboard. http://sketchshortcuts.com/

**Comment by alechp** [comment]
@craigmdennis Thank you. Huge help. 

And thank you to @nefaurk for providing the original Select Parent... I use this 50+ times a day. Awesome work.

**Comment by craigmdennis** [comment]
Ok while `ESC` does this for a single artboard, I do use this plugin when selecting multiple elements on multiple artboards and wanting to then select all of the parents. So still very useful :)

**Comment by nefaurk** [comment]
Should be resolved in https://github.com/nefaurk/select-parent-artboards/releases/tag/v1.1
