### ISSUE TITLE
Doesn't work on symbols

### ISSUE THREAD

**Issue by jberk-godaddy** [nefaurk/select-parent-artboards#6]
If you select a symbol then run the plugin, it does not select the artboard.

**Comment by nefaurk** [comment]
Thanks for filing this! It looks like I wasn't dealing with that case properly (partially due to https://github.com/BohemianCoding/SketchAPI/issues/73). I'm going to push some code that works around that issue in a bit!

**Comment by nefaurk** [comment]
Should be fixed in v1.2. Can you update and let me know if that fixes your issue, @xzab ?

**Comment by jberk-godaddy** [comment]
Looks good now!  Thank you!

**Comment by nefaurk** [comment]
Great, thanks for checking!
